name: Publish browser extension zip files
on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: chrome/
          dest: chrome-extension.zip
      - uses: vimtor/action-zip@v1
        with:
          files: firefox/
          dest: firefox-extension.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chrome-extension.zip
            firefox-extension.zip
